
PREDICT_HIGHEST_CLOSING = 'closing'
PREDICT_HIGHEST_CLOSING_PERCENT = 'closing_percent'
PREDICT_TREND = 'trend'
FILE_NPY = 0
FILE_CSV = 1

BUY_ORDER_LIMIT = 0
BUY_ORDER_STOP = 1
SELL_ORDER_LIMIT = 2
SELL_ORDER_STOP = 3

ERR_INSUFFICIENT_BALANCE = -1
ERR_OUTSIDE_SIMULATION = -2
ERR_INVALID_QUOTE = -3
ERR_GENERAL = -4